version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: practice
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  order-service:
    build: .
    container_name: peaceful_allen
    ports:
      - "8080:8081"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/practice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test

volumes:
  mysql_data: